package by.training.nc.dev3.enums;

public enum AdminAct {
    ADD, REMOVE, VIEW, REMOVEALL, CHECK, VIEWORDER, VIEWBLACKLIST,
    VIEWARCHIVE, VIEWADMINS, REMOVEADMIN, EDITADMIN, VIEWCUSTOMERS,
    REMOVECUSTOMER, EDITCUSTOMER;
}
